### ISSUE TITLE
Arm/aarch64 iso for parallels running under Apple Silicon macOS?

### ISSUE THREAD

**Issue by poetaman** [PureDarwin/PD-17.4-Beta#11]
Where can I find a aarch64 iso that can be run under parallels on Apple Silicon macOS?

**Comment by hideout** [comment]
nowhere yet sorry

Am Do., 16. Dez. 2021 um 00:09 Uhr schrieb reportaman <
***@***.***>:

**Comment by Hawk2811** [comment]
it even seems that the project has been stopped since 2009

**Comment by Hawk2811** [comment]
will puredarwin ever come back because i also thought of it a hackintosh or open source darwin system for arm

**Comment by ninjadev64** [comment]
> it even seems that the project has been stopped since 2009

more like 2015

**Comment by hideout** [comment]
yes we will come back! and we never were really gone .. but the main devs.
are busy with other projects atm.

stay tuned.

Thanks for your message



Am Mi., 26. Jan. 2022 um 19:28 Uhr schrieb ninjadev64 <
***@***.***>:
