### ISSUE TITLE
How to install unix software on it?

### ISSUE THREAD

**Issue by njlyf2011** [PureDarwin/PD-17.4-Beta#3]
I originally wanted to install the software through macports or homebrew and found that it didn't work. Then I want to compile with gcc/clang and I found no. I don't know what to do.

**Comment by csekel** [comment]
We removed old image about to upload a new one with clang and such installed.

**Comment by njlyf2011** [comment]
Thanks!

**Comment by csekel** [comment]
This image now has compiler you can sideload the src using what's in the readme.
