### ISSUE TITLE
Can't boot vmdk - Can't find boot file /mach_kernel

### ISSUE THREAD

**Issue by spacerace** [PureDarwin/PD-17.4-Beta#7]
Hi,

I just wanted to try your vmdk and I am having problems to boot it.

![err](https://user-images.githubusercontent.com/3340904/51903137-dc191a80-23bb-11e9-9c07-b4e92102932c.png)

I had to change the qemu command line, as I dont have enough memory to boot with 8gigs. My test system only has 2G ram, so I changed to 256 and 512. Both are not changing anything.

What am I doing wrong? 

Thanks for reading!
Nils

**Comment by CryptoManiac** [comment]
Same here. Looks like there is no kernel file or it has another name.

**Comment by csekel** [comment]
You need to have 2GB or system won't boot.

**Comment by spacerace** [comment]
Thanks for you answer!

I think I did an additional mistake. If you use i386-system-qemu (accidentially, just used to type this one...) rather than 64bit qemu same thing happens.

Nils
