### ISSUE TITLE
Can't set up ethernet port with iftab

### ISSUE THREAD

**Issue by StEvUgnIn** [PureDarwin/PD-17.4-Beta#8]
Hello,
I would like to set my NAT ethernet connection in Virtualbox as en0 to access the internet from my PureDarwin VM. 

Thank you very much. 

this is the current output of ifconfig for the virtual connection set on NAT:
![image](https://user-images.githubusercontent.com/7686916/55952968-2be94d00-5c5b-11e9-8bb0-f9d36c9f73ad.png)

**Comment by libsystem-ethan** [comment]
I don't think the VM has working Ethernet support yet. The driver (`AppleIntelE1000e.kext` has been compiled and is in `/System/Library/Extensions`) however the rest of the networking stack (e.g. the (x)inetd functionality provided by launchd) is missing. Until these components get built into the VM, the only way to get stuff in and out of the VM would be to mount the disk image and make changes there.

**Comment by StEvUgnIn** [comment]
> I don't think the VM has working Ethernet support yet. The driver (`AppleIntelE1000e.kext` has been compiled and is in `/System/Library/Extensions`) however the rest of the networking stack (e.g. the (x)inetd functionality provided by launchd) is missing. Until these components get built into the VM, the only way to get stuff in and out of the VM would be to mount the disk image and make changes there.

Would you be interested to work this summer on implementing a networking stack for PureDarwin 18 (mojave) and master branch?

**Comment by csekel** [comment]
That would be nice to get that up, we are working on a mojave release. Would you like to possibly join our team?

**Comment by hideout** [comment]
please join our team... get in contact with us over irc #puredarwin on
freenode project

cheers from berlin

ferdinand (bart)

Am Mi., 19. Juni 2019 um 17:55 Uhr schrieb InSaneDarwin <
notifications@github.com>:
